mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^rent/', include('rent.urls', namespace="rent")),
    url(r'^admin/', admin.site.urls),
]

rent/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^view_contracts$', views.view_contracts, name='view_contracts'),
    url(r'^view_invoices$', views.view_invoices, name='view_invoices'),
    url(r'^view_customers$', views.view_customers, name='view_customers'),
    url(r'^view_vehicles$', views.view_vehicles, name='view_vehicles'),

    url(r'^open_contract$', views.open_contract_view, name='open_contract'),
    url(r'^close_contract$', views.close_contract_view, name='close_contract'),
]

rent/models.py
from django.db import models

class Customer(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    vat_code = models.CharField(max_length=100)
    ssn = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    driving_licence = models.CharField(max_length=100)


# Create your models here.
class Vehicle(models.Model):
    name = models.CharField(max_length=100)
    plate = models.CharField(max_length=12)
    miles = models.IntegerField()

    def __str__(self):
        return "{Name: '" + str(self.name) + " plate " + str(self.plate) + " cur km " + str(self.miles) + "}"


class Contract(models.Model):
    customer = models.ForeignKey(Customer)
    vehicle = models.ForeignKey(Vehicle)
    contract_start = models.DateTimeField()
    contract_expected_end = models.DateTimeField()
    contract_real_end = models.DateTimeField()
    miles_in = models.IntegerField()
    miles_out = models.IntegerField()


class Invoice(models.Model):
    contract = models.ForeignKey(Contract)
    invoice_number = models.IntegerField()
    invoice_date = models.DateTimeField()
    invoice_total = models.DecimalField(max_digits=12, decimal_places=2)
    is_payed = models.BooleanField(default = False)
    date_payed = models.DateTimeField()

rent/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Vehicle, Customer, Invoice, Contract

def index(request):
    context = {'clients_list': {}}
    return render(request, 'rent/welcome.html', context)

def open_contract_view(request):
    #to open a contract I have to make a list of customers and vehicles
    list_customers = Customer.objects.all()
    list_vehicles = Vehicle.objects.all()

    context = {'customers_list': list_customers, 'vehicles_list': list_vehicles}
    return render(request, 'rent/open_contract.html', context)


def close_contract_view(request):
    ht = HttpResponse("da fare... chiudi contratto")
    return ht

def view_contracts(request):
    ht = HttpResponse("Qui ci sono i contratti")
    return ht

def view_invoices(request):
    ht = HttpResponse("Qui ci sono le fatture")
    return ht

def view_customers(request):
    ht = HttpResponse("Qui ci sono i clienti")
    return ht

def view_vehicles(request):
    ht = HttpResponse("Qui ci sono i mezzi")
    return ht

rent/templates/rent/open_contract.html
<h1>Aggiungi un nuovo contratto:</h1>



<form method="post" action="{% url 'rent:open_contract_post' %}">
{% csrf_token %}
<label for="id_cliente">Cliente:</label>

<select id='customer'>
   {% for customer in customers_list %}
   
   <option value="{{ customer.id }}">{{ customer.name  }}, {{ customer.surname }} </option>

   {% endfor %}

</select>

<p>

<label for="id_q">Veicolo:</label>
<select id='vehicle'>
   {% for vehicle in vehicles_list %}
   
   <option value="{{ vehicle.id }}">{{ vehicle.name  }} Targa: {{ vehicle.plate}} </option>

   {% endfor %}

</select>




<input type="submit" value="Apri!"/>
</form>

rent/templates/rent/welcome.html
<h1>Ciao Sabrina,</h1>

<p>Qui puoi iniziare a lavorare con il computer, non sei contenta? Così non hai più scuse... </p>

<p>Dimmi cosa vuoi fare:</p>

<ul>
<a href="{% url 'rent:view_contracts' %}"> Fammi vedere i contratti.</a>
</ul>
<ul>
<a href="{% url 'rent:view_invoices' %}"> Fammi vedere le fatture.</a>
</ul>
<ul>
<a href="{% url 'rent:view_customers' %}"> Fammi vedere i clienti.</a>
</ul>
<ul>
<a href="{% url 'rent:view_vehicles' %}"> Fammi vedere i mezzi.</a>
</ul>
<ul>
<a href="{% url 'rent:open_contract' %}"> Voglio aprire un contratto.</a>
</ul>
<ul>
<a href="{% url 'rent:close_contract' %}"> Voglio chiudere un contratto.</a>
</ul>